import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const textInput = z.object({
  text: z.string().min(1).max(20000),
  apiKey: z.string().min(10).max(400).optional(),
});

const HUMANIZE_PROMPT = `You are a text humanizer. Rewrite the user's text so it reads as natural, human-written prose that bypasses AI-detection heuristics.

RULES:
- Preserve meaning, facts, and intent exactly. Never add or remove information.
- Vary sentence length and rhythm (mix short punchy sentences with longer flowing ones — "burstiness").
- Increase lexical unpredictability ("perplexity"): swap generic AI-favored words (delve, leverage, furthermore, moreover, in conclusion, it's important to note, tapestry, navigate, realm) for plain alternatives.
- Use contractions, occasional informal connectors (so, but, and at sentence starts when natural), and the active voice.
- Drop hedging filler and over-polished transitions. Keep the user's original tone (formal stays formal, casual stays casual).
- Do NOT add a preface, explanation, or markdown. Output ONLY the rewritten text.`;

const DETECT_PROMPT = `You are an AI-text detector. Analyze the user's text and estimate the probability it was generated by an AI language model.

Consider: perplexity (word predictability), burstiness (sentence-length variance), repetitive structures, generic transitions, overuse of words like "delve / leverage / moreover / it's important to note", uniform paragraph rhythm, lack of personal voice or specific lived detail.

Respond ONLY with valid JSON, no markdown fences, in this exact shape:
{
  "ai_probability": <integer 0-100>,
  "verdict": "<HUMAN | LIKELY HUMAN | MIXED | LIKELY AI | AI>",
  "confidence": "<low | medium | high>",
  "signals": ["<short signal 1>", "<short signal 2>", "<short signal 3>"],
  "notes": "<one or two sentence explanation>"
}`;

async function callGateway(system: string, user: string, userKey?: string) {
  const apiKey = userKey || process.env.LOVABLE_API_KEY;
  if (!apiKey) throw new Error("No API key. Open settings and paste your key.");

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "claude-haiku-4-5",
      max_tokens: 1024,
      system,
      messages: [{ role: "user", content: user }],
    }),
  });

  if (!res.ok) {
    if (res.status === 429) throw new Error("Rate limit hit. Wait a moment and try again.");
    if (res.status === 402) throw new Error("AI credits exhausted.");
    if (res.status === 401 || res.status === 403) throw new Error("Invalid API key. Update it in settings.");
    throw new Error("AI gateway returned an error.");
  }
  const json = (await res.json()) as { content?: Array<{ text?: string }> };
  return json.content?.[0]?.text ?? "";
}

export const humanizeText = createServerFn({ method: "POST" })
  .inputValidator((i: unknown) => textInput.parse(i))
  .handler(async ({ data }) => {
    const content = await callGateway(HUMANIZE_PROMPT, data.text, data.apiKey);
    return { content: content.trim() };
  });

export const detectAiText = createServerFn({ method: "POST" })
  .inputValidator((i: unknown) => textInput.parse(i))
  .handler(async ({ data }) => {
    const raw = await callGateway(DETECT_PROMPT, data.text, data.apiKey);
    // Strip accidental code fences
    const cleaned = raw.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "").trim();
    type DetectResult = {
      ai_probability: number;
      verdict: string;
      confidence: string;
      signals: string[];
      notes: string;
    } | null;
    let parsed: DetectResult = null;
    try {
      parsed = JSON.parse(cleaned) as DetectResult;
    } catch {
      const m = cleaned.match(/\{[\s\S]*\}/);
      if (m) {
        try { parsed = JSON.parse(m[0]) as DetectResult; } catch { /* ignore */ }
      }
    }
    return { raw: cleaned, result: parsed };
  });
